### ISSUE TITLE
App. Crashes after a few seconds of execution.

### ISSUE THREAD

**Issue by luisan00** [btcven/locha-mesh-chat#137]
The application crashes after a few seconds of execution.

**To Reproduce**
1. Setup the account and add your pin.
2. Wait a few seconds.
3. The application crashes.

If the application opens after the point 3. crashes again.

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s10
 - Android  10

**Comment by xkevin190** [comment]
this problem was fixed in the PR  #138
