### ISSUE TITLE
Profile Image Request

### ISSUE THREAD

**Issue by xkevin190** [btcven/locha-mesh-chat#26]
## Profile Image Request
When we add a user to the contact list, we must now add an image of our gallery.
It would be interesting if the image could be requested from the user through its **UID**

### How does it work?

1. Add user using **UID**, hereinafter we will call **YOUR-UID **.
2. ** Profile picture is requested from ** YOUR-UID **, the application includes ** MY-UID **
2.1. ** YOUR-UID ** verifies that ** MY-UID ** is a valid user (it is in your contact list)
2.1.1 If in contacts; Send image
2.1.2 If not: refuse

**Comment by luisan00** [comment]
Fixed in PR #39
