### ISSUE TITLE
Does it use any external service or storage?

### ISSUE THREAD

**Issue by ugintl** [btcven/locha-mesh-chat#49]
Does this app use any external services?

Where is the data saved like user credentials etc?

**Comment by jeandudey** [comment]
All data is stored on the locally on the user phone without sending any data to a external server, the main idea is that all communication happens offline on the Mesh Network.

All sensible user data (credentials) are stored on the phone. Mainly the seed words (needed to generate and identity) and the user pin.

**Comment by ugintl** [comment]
I visited the locha website. There is a device and a pre-order button. Do I need that device or it will work app to app?

**Comment by jeandudey** [comment]
>Do I need that device or it will work app to app?

The device is needed for communication in the Locha Mesh using the app, there aren't plans for now to iconnect this chat App to internet for now. The device it's being actively developed, both firmware and hardware (open source) and isn't only limited to this application, in theory other services can be implemented with those devices.

There will be a DIY (for experienced users, and with a lower transmit power), and a custom board developed by locha.io that is more easy to setup, and with a higher transmit power (a custom design is needed for this). Both will be compatible.
